# Generated by Django 3.2.8 on 2021-11-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='매칭상태')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.PositiveSmallIntegerField(verbose_name='별점')),
                ('comment', models.TextField(verbose_name='설명')),
                ('doctor', models.ForeignKey(db_column='doctor', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='doctor.doctor')),
                ('matching', models.OneToOneField(db_column='matching', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='package.matching')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100, verbose_name='상품명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('count', models.PositiveSmallIntegerField(verbose_name='횟수')),
                ('description', models.TextField(verbose_name='상품 설명')),
                ('counseling_time', models.IntegerField(verbose_name='상담 시간')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('doctor', models.ForeignKey(db_column='doctor', on_delete=django.db.models.deletion.PROTECT, related_name='package', to='doctor.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='matching',
            name='package',
            field=models.ForeignKey(db_column='package', on_delete=django.db.models.deletion.PROTECT, related_name='matching', to='package.package'),
        ),
        migrations.AddField(
            model_name='matching',
            name='patient',
            field=models.ForeignKey(db_column='patient', on_delete=django.db.models.deletion.CASCADE, related_name='matching', to='patient.patient'),
        ),
    ]
