# Generated by Django 3.2.8 on 2021-10-29 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('count', models.IntegerField(verbose_name='횟수')),
                ('description', models.TextField(verbose_name='상품 설명')),
                ('counseling_time', models.IntegerField(verbose_name='상담 시간')),
                ('is_active', models.BooleanField(verbose_name='활성')),
                ('doctor', models.ForeignKey(db_column='doctor', on_delete=django.db.models.deletion.CASCADE, related_name='package', to='doctor.doctor')),
            ],
        ),
    ]
