# Generated by Django 3.2.8 on 2021-10-30 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='횟수'),
        ),
        migrations.AlterField(
            model_name='package',
            name='doctor',
            field=models.ForeignKey(db_column='doctor', on_delete=django.db.models.deletion.PROTECT, related_name='package', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(verbose_name='가격'),
        ),
    ]
