# Generated by Django 3.2.8 on 2021-10-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20211030_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성'),
        ),
    ]
