# Generated by Django 3.2.8 on 2021-11-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('package', '0003_alter_package_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False, verbose_name='매칭상태')),
                ('package', models.ForeignKey(db_column='package', on_delete=django.db.models.deletion.PROTECT, related_name='matching', to='package.package')),
                ('patient', models.ForeignKey(db_column='patient', on_delete=django.db.models.deletion.CASCADE, related_name='matching', to='patient.patient')),
            ],
        ),
    ]
