# Generated by Django 3.2.8 on 2021-11-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('package', '0004_matching'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.PositiveSmallIntegerField(verbose_name='별점')),
                ('comment', models.TextField(verbose_name='설명')),
                ('doctor', models.ForeignKey(db_column='doctor', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='doctor.doctor')),
            ],
        ),
    ]
