# Generated by Django 3.2.8 on 2021-11-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='state',
            field=models.BooleanField(default=True, verbose_name='매칭상태'),
        ),
    ]
