# Generated by Django 3.2.8 on 2021-10-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionform',
            name='question_form_name',
            field=models.CharField(default='', max_length=50, verbose_name='문답지이름'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.JSONField(verbose_name='답변'),
        ),
    ]
