# Generated by Django 3.2.8 on 2021-10-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20211027_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='문답일자'),
        ),
    ]
