# Generated by Django 3.2.8 on 2021-10-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user_id',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user'),
        ),
    ]
