# Generated by Django 3.2.8 on 2021-10-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='user',
        ),
    ]
