# Generated by Django 3.2.8 on 2021-10-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211018_2153'),
        ('patient', '0003_rename_user_id_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient', serialize=False, to='user.user'),
        ),
    ]
