# Generated by Django 3.2.8 on 2021-10-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor', serialize=False, to='user.user')),
                ('hospital_address', models.CharField(max_length=200, null=True, verbose_name='병원주소')),
                ('is_verified', models.BooleanField(null=True, verbose_name='인가여부')),
                ('self_pr', models.TextField(null=True, verbose_name='자기소개')),
            ],
        ),
    ]
