# Generated by Django 3.2.8 on 2021-11-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='프로필사진'),
        ),
    ]
