# Generated by Django 3.2.8 on 2021-10-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=False, null=True, verbose_name='인가여부'),
        ),
    ]
