# Generated by Django 3.2.8 on 2021-11-07 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0002_alter_review_matching'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateField(verbose_name='상담일자및시간')),
                ('is_valid', models.BooleanField(verbose_name='승인여부')),
                ('end_datetime', models.DateField(verbose_name='상담종료및시간')),
                ('state', models.BooleanField(verbose_name='상담상태')),
                ('matching', models.ForeignKey(db_column='matching', on_delete=django.db.models.deletion.PROTECT, related_name='counseling_schedule', to='package.matching')),
            ],
        ),
        migrations.CreateModel(
            name='CounselingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(verbose_name='처방')),
                ('doctor_memo', models.TextField(verbose_name='의사 메모')),
                ('content', models.TextField(verbose_name='상담내용')),
                ('counseling_schedule', models.OneToOneField(db_column='counseling_result', on_delete=django.db.models.deletion.PROTECT, related_name='counseling_result', to='counseling.counselingschedule')),
            ],
        ),
    ]
