# Generated by Django 3.2.8 on 2021-11-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingschedule',
            name='state',
            field=models.BooleanField(default=False, verbose_name='상담상태'),
        ),
    ]
