name: Update lambda with Zappa

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Create virtual env
        run: |
          pip install virtualenv
          virtualenv --python=3.8 zappa-deploy
          source zappa-deploy/bin/activate

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Check credential
        run: |
          sudo aws configure list-profiles

      - name: Install Dependencies
        run: |
          source zappa-deploy/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy with Zappa
        env:
          VIRTUAL_ENV: ./zappa-deploy
        run: |
          source zappa-deploy/bin/activate
          pip install zappa
          python manage.py makemigrations
          zappa update dev
          zappa manage dev migrate
